name: 自动部署新版本到服务器
# 在特定 tag 被 push 以后被触发
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      # checkout 代码
      - uses: actions/checkout@v2
      # 创建 .env 文件
      # build docker image
      # start the app
      - name: "create env file"
        run: |
          touch .env
          echo NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }} >> .env
          echo API_BASE_URL=${{ secrets.API_BASE_URL }} >> .env
          echo DASHSCOPE_API_KEY=${{ secrets.DASHSCOPE_API_KEY }} >> .env
          echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env
      # 使用阿里云ACR 完成 docker login
      - name: Login to Aliyun Container Registry (ACR)
        uses: aliyun/acr-login@v1
        with:
          login-server: crpi-yacuoj1e11qkasck.cn-beijing.personal.cr.aliyuncs.com
          region-id: cn-beijing
          username: "${{ secrets.ACR_USERNAME }}"
          password: "${{ secrets.ACR_PASSWORD }}"
      #使用正确的阿里云 tag 进行 docker build
      - name: Build image for docker
        run: docker build --tag "crpi-yacuoj1e11qkasck.cn-beijing.personal.cr.aliyuncs.com/jiaozenghui/next-blog:${{github.ref_name}}" .
      - name: Psuh Image to ACR
        run: docker push crpi-yacuoj1e11qkasck.cn-beijing.personal.cr.aliyuncs.com/jiaozenghui/next-blog:${{github.ref_name}}
      # 测试查找并替换
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "{{tag}}"
          replace: ${{github.ref_name}}
          include: "docker-compose-online.yml"
      # 拷贝必须文件到一个文件夹，包括.env， docker-compose-online.yml， mongo-entrypoint
      - name: "copy necessary files in to one folder"
        run: |
          mkdir next-blog
          cp .env docker-compose-online.yml next-blog
          ls -a next-blog
      # 通过 scp 拷贝必须文件到服务器
      - name: "copy next-blog folder via scp"
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.SSH_USER}}
          password: ${{secrets.SSH_PWD}}
          source: "next-blog"
          target: "~"
      # 通过 SSH 登录然后重启服务器
      - name: executing ssh and restart docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.SSH_USER}}
          password: ${{secrets.SSH_PWD}}
          script_stop: true
          # * 登录阿里云 ACR
          # 停止服务 docker-compose down
          # 清理工作
          script: |
            docker login --username ${{secrets.ACR_USERNAME}} --password=${{secrets.ACR_PASSWORD}} crpi-yacuoj1e11qkasck.cn-beijing.personal.cr.aliyuncs.com
            cd ~/next-blog/
            docker compose -f docker-compose-online.yml down
            docker compose -f docker-compose-online.yml up -d
            rm -rf .env
            docker logout crpi-yacuoj1e11qkasck.cn-beijing.personal.cr.aliyuncs.com
